# Generated by Django 6.0 on 2026-01-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
